#!/usr/bin/env ruby

require "erb"
require "digest/md5"

TEMPLATE = File.join(__dir__, "cronjob-sync.erb")
SOURCES = [
  "timemachine",
  "backups",
  "shared",
]

MINUTES_BETWEEN_JOBS=4 * 60

template = File.read(TEMPLATE)
SOURCES.each_with_index do |source, i|
  minutes_offset = i * (MINUTES_BETWEEN_JOBS / SOURCES.length)
  hour = minutes_offset / 60
  minute = minutes_offset % 60
  cj = ERB.new(template)
  filename = File.join(__dir__, "cronjob-sync-#{source}.yaml")
  puts "Writing #{filename}"
  File.write(filename, cj.result(binding))
end
